version: '3.8'

services:
  postgres_certification:
    container_name: authenticationAPI
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=authenticationAPI